media-organizer: 
  source-directory: \\server\share\source
  test-mode: false
  mode: DUPLICATE_HUNTER  #TO_QUARTERLY_FOLDERS, RENAME-FILES
  quarterly-folders-config:
    destination-directory: \\server\share\dest
    date-source: METADATA_THEN_FILE_CREATION
    delete-duplicates: false
    log-all-tags: false
    file-extensions:  
    - jpg
    - jpeg
    - mov
    - mp4
    - JPG
    - JPEG
    - MOV
    - MP4 
  duplicate-hunter-config:
    file-extensions:
    - jpg
    - jpeg
    - JPG
    - JPEG
  rename-files-config:
    replace: " - Copy"
    replace-with: ""
