fileorganizer: 
  sourcedir: c:\tmp\test\source
  destdir: c:\tmp\test\dest
  testmode: false
  showalltags: false
  metadataonly: false
  deleteduplicates: true
  extensions:
    - jpg
    - jpeg
    - mov
    - png
    - JPG
    - JPEG
    - PNG
    - MOV
